config/routes.rb
It490::Application.routes.draw do
  resources :aircarft_types

  devise_for :users

  root 'static_pages#home'

  resources :shipment_requests
  get 'shipments' => 'shipments#index'
  get 'cargo' => 'cargo#index'
  resources :aircrafts
  resources :aircraft_types
  resources :aircrews
  resources :airports
  resources :flights
  resources :pilots
  resources :navigators
  resources :user_manager

  

end

app/models/aircraft.rb
class Aircraft < ActiveRecord::Base
	validates :tail_number, presence: true
	validates :fuel_amount, presence: true

	belongs_to :aircraft_type

	def self.search(search)
		if search
			joins(:aircraft_type).where('LOWER(tail_number) LIKE LOWER(?) or LOWER(aircraft_types.name) LIKE LOWER(?)', "%#{search}%", "%#{search}%")
		else
			scoped
		end
	end

	def pretty_name
		self.tail_number + " - " + self.aircraft_type.name
	end 
end

app/models/aircraft_type.rb
class AircraftType < ActiveRecord::Base
	validates :code, presence: true
	validates :name, presence: true

	def self.search(search)
		if search
			where('LOWER(name) LIKE LOWER(?) or LOWER(code) LIKE LOWER(?)', "%#{search}%", "%#{search}%")
		else
			scoped
		end
	end
end

app/controllers/aircrafts_controller.rb
class AircraftsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin_filter

  before_action :set_aircraft, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  layout 'secure'

  # GET /aircrafts
  # GET /aircrafts.json
  def index
     @aircrafts = Aircraft.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end

  # GET /aircrafts/1
  # GET /aircrafts/1.json
  def show
  end

  # GET /aircrafts/new
  def new
    @aircraft = Aircraft.new
  end

  # GET /aircrafts/1/edit
  def edit
  end

  # POST /aircrafts
  # POST /aircrafts.json
  def create
    @aircraft = Aircraft.new(aircraft_params)

    respond_to do |format|
      if @aircraft.save
        format.html { redirect_to @aircraft, notice: 'Aircraft was successfully created.' }
        format.json { render action: 'show', status: :created, location: @aircraft }
      else
        format.html { render action: 'new' }
        format.json { render json: @aircraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aircrafts/1
  # PATCH/PUT /aircrafts/1.json
  def update
    respond_to do |format|
      if @aircraft.update(aircraft_params)
        format.html { redirect_to @aircraft, notice: 'Aircraft was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @aircraft.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aircrafts/1
  # DELETE /aircrafts/1.json
  def destroy
    @aircraft.destroy
    respond_to do |format|
      format.html { redirect_to aircrafts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aircraft
      @aircraft = Aircraft.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aircraft_params
      params.require(:aircraft).permit(:id, :tail_number, :aircraft_type_id, :fuel_amount)
    end

    def sort_column
      Aircraft.column_names.include?(params[:sort]) ? params[:sort] : "tail_number"
    end
  
    def sort_direction
       %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/aircrafts_helper.rb
module AircraftsHelper
end

app/views/aircrafts/_aircrafts.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= will_paginate @aircrafts %>

<table width="600">
	<thead>
		<tr>
			<th><%= sortable "tail_number", "Tail Number" %></th>
			<th><%= sortable "aircraft_type", "Aircraft Type" %></th>
			<th><%= sortable "fuel_amount", "Fuel Amount" %></th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @aircrafts.each do |aircraft| %>
		<tr>
			<td><%= aircraft.tail_number rescue "n/a" %></td>
			<td><%= aircraft.aircraft_type.name rescue "n/a" %>
			<td><%= aircraft.fuel_amount rescue "n/a" %></td>
			<td><%= link_to 'Show', aircraft %></td>
			<td><%= link_to 'Edit', edit_aircraft_path(aircraft) %></td>
			<td><%= link_to 'Destroy', aircraft, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %></tbody>
</table>

<%= will_paginate @aircrafts %>

<br>

app/views/aircrafts/_form.html.erb
<%= form_for(@aircraft) do |f| %>
  <% if @aircraft.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aircraft.errors.count, "error") %> prohibited this aircraft from being saved:</h2>

      <ul>
      <% @aircraft.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :tail_number, 'Tail Number' %><br>
    <%= f.text_field :tail_number, :placeholder => 'Tail Number' %>
  </div>

  <div class="field">
    <%= f.label :aircraft_type_id, 'Aircraft Type' %><br>
    <%= f.select :aircraft_type_id, AircraftType.all.collect {|a| [a.name, a.id]} -%>
  </div>

  <div class="field">
    <%= f.label :fuel_amount, 'Fuel Amount' %><br>
    <%= f.text_field :fuel_amount, :placeholder => 'Fuel Amount' %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button big gh-black'%>
  </div>
<% end %>

app/views/aircrafts/edit.html.erb
<h1>Edit Aircraft</h1>

<%= render 'form' %>

<%= link_to 'Show', @aircraft %> |
<%= link_to 'Back', aircraft_path %>

app/views/aircrafts/index.html.erb
<h1>Listing of Aircraft</h1>

<div>
  <%= link_to 'New Aircraft', new_aircraft_path %>
</div>

<br>

<%= form_tag aircrafts_path, :method => 'get', :id => "aircrafts_search" do %>
  <div>
    <%= text_field_tag :search, params[:search], :placeholder => 'Search by Tail Number', :size => 45 %>
    <%= submit_tag "Search", :name => nil, :class => 'button big gh-black' %>
  </div>
  <div id="aircrafts"><%= render 'aircrafts' %></div>
<% end %>

app/views/aircrafts/index.js.erb
$("#aircrafts").html("<%= escape_javascript(render("aircrafts")) %>");

app/views/aircrafts/new.html.erb
<h1>New Aircraft</h1>

<%= render 'form' %>

<%= link_to 'Back', aircrafts_path %>

app/views/aircrafts/show.html.erb
<h1>Aircraft Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Tail Number:</strong>
  <%= @aircraft.tail_number rescue "n/a" %>
</p>

<p>
  <strong>Aircraft Type:</strong>
  <%= @aircraft.aircraft_type.name rescue "n/a" %>
</p>

<p>
  <strong>Fuel Amount:</strong>
  <%= @aircraft.fuel_amount rescue "n/a" %>
</p>

<%= link_to 'Edit', edit_aircraft_path(@aircraft) %> |
<%= link_to 'Back', aircrafts_path %>