config/routes.rb
It490::Application.routes.draw do
  resources :aircarft_types

  devise_for :users

  root 'static_pages#home'

  resources :shipment_requests
  get 'shipments' => 'shipments#index'
  get 'cargo' => 'cargo#index'
  resources :aircrafts
  resources :aircraft_types
  resources :aircrews
  resources :airports
  resources :flights
  resources :pilots
  resources :navigators
  resources :user_manager

  

end

app/models/flight.rb
class Flight < ActiveRecord::Base
	belongs_to :aircraft
	belongs_to :origin, :class_name => "Airport"
	belongs_to :destination, :class_name => "Airport"
	belongs_to :cargo
	belongs_to :aircrew
	belongs_to :user

	validates :aircraft, presence: true
	validates :origin, presence: true
	validates :destination, presence: true
	validates :cargo, presence: true
	validates :aircrew, presence: true
	validates :number, presence: true

	def self.search(search)
		if search
			where('LOWER(number) LIKE LOWER(?)', "%#{search}%")
		else
			scoped
		end
	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin_filter

  before_action :set_flight, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  layout 'secure'

  # GET /flights
  # GET /flights.json
  def index
     @flights = Flight.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    req_id = params[:shipment_request_id]
    unless req_id.nil?
      shipment_request = ShipmentRequest.find(params[:shipment_request_id])

      @flight = Flight.new
      @flight.user_id = shipment_request.user_id
      @flight.request_id = shipment_request.id
      @flight.origin_id = shipment_request.origin_id
      @flight.destination_id = shipment_request.destination_id
      @flight.departure_time = shipment_request.desired_departure_datetime
      @flight.arrival_time = (shipment_request.desired_departure_datetime + 6.hours).to_datetime

      cargo = Cargo.new
      cargo.weight = shipment_request.cargo_weight
      cargo.contents = shipment_request.cargo_contents

      @flight.cargo = cargo
    else
      @flight = Flight.new
      cargo = Cargo.new
      @flight.cargo = cargo
    end

  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    logger.info "flight_params: #{flight_params.inspect}"

    # This is hack, to get around the type mismatch, don't fully understand strong params yet
    @cargo = Cargo.new
    @cargo.weight = flight_params[:cargo][:weight]
    @cargo.contents = flight_params[:cargo][:contents]
    logger.info "@cargo: #{@cargo.inspect}"
    @cargo.save

    @flight = Flight.new
    @flight.number = flight_params[:number]
    @flight.user_id = flight_params[:user_id]
    @flight.request_id = flight_params[:request_id]
    @flight.aircraft_id = flight_params[:aircraft_id]
    @flight.origin_id = flight_params[:origin_id]
    @flight.destination_id = flight_params[:destination_id]
    @flight.departure_time = DateTime.new(flight_params["departure_time(1i)"].to_i, flight_params["departure_time(2i)"].to_i, flight_params["departure_time(3i)"].to_i, flight_params["departure_time(4i)"].to_i, flight_params["departure_time(5i)"].to_i)
    @flight.arrival_time = DateTime.new(flight_params["arrival_time(1i)"].to_i, flight_params["arrival_time(2i)"].to_i, flight_params["arrival_time(3i)"].to_i, flight_params["arrival_time(4i)"].to_i, flight_params["arrival_time(5i)"].to_i)
    @flight.cargo_id = @cargo.id
    @flight.aircrew_id = flight_params[:aircrew_id]

    logger.info "@flight: #{@flight.inspect}"

    respond_to do |format|

      if @flight.save
        req_id = params[:shipment_request_id]
        unless req_id.nil?
          request = ShipmentRequest.find(@flight.request_id)
          request.is_accepted = true
          request.save
        end

        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render action: 'show', status: :created, location: @flight }
      else
        format.html { render action: 'new' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:request_id, :user_id, :aircraft_id, :number, :aircrew_id, :origin_id, :destination_id, :departure_time, :arrival_time, cargo: [:weight, :contents])
    end

    def sort_column
      Flight.column_names.include?(params[:sort]) ? params[:sort] : "number"
    end
  
    def sort_direction
       %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/views/flights/_flights.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= will_paginate @flights %>

<table width="600">
	<thead>
		<tr>
			<th><%= sortable "number", "Flight Number" %></th>
			<th><%= sortable "origin" %></th>
			<th><%= sortable "destination" %></th>
			<th><%= sortable "departure_time" %></th>
			<th><%= sortable "arrival_time" %></th>
			<th>Cargo Owner</th>
			<th>Cargo Contents</th>
			<th>Cargo Weight</th>
			<th>Pilot</th>
			<th>Navigator</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @flights.each do |flight| %>
		<tr>
			<td><%= flight.number rescue "n/a" %></td>
			<td><%= flight.origin.pretty_name rescue "n/a" %></td>
			<td><%= flight.destination.pretty_name rescue "n/a" %></td>
			<td><%= flight.departure_time rescue "n/a" %></td>
			<td><%= flight.arrival_time rescue "n/a" %></td>
			<td><%= flight.user.email rescue "n/a" %></td>
			<td><%= flight.cargo.contents rescue "n/a" %></td>
			<td><%= flight.cargo.weight rescue "n/a" %></td>
			<td><%= "#{flight.aircrew.pilot.lname}, #{flight.aircrew.pilot.fname}" rescue "n/a" %></td>
			<td><%= "#{flight.aircrew.navigator.lname}, #{flight.aircrew.navigator.fname}" rescue "n/a" %></td>
			<td><%= link_to 'Show', flight %></td>
			<td><%= link_to 'Edit', edit_flight_path(flight) %></td>
			<td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %></tbody>
</table>

<%= will_paginate @flights %>

<br>

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h2>User Information</h2>
  <div class="field">
    <label for="flight_user_id">Requestor</label><br>
    <%= f.collection_select :user_id, User.all, :id, :email %>
  </div>

  <h2>Cargo Information</h2>
  <%= f.fields_for :cargo, @flight.cargo do |c| %>

  <div class="field">
    <%= c.label :weight %><br>
    <%= c.text_field :weight %>
  </div>
  <div class="field">
    <%= c.label :contents %><br>
    <%= c.text_area :contents, :cols => "40", :rows => "6" %>
  </div>
  <% end %>

  <h2>Flight Information</h2>
  <div class="field">
    <%= f.label :aircraft_id, 'Aircraft' %><br>
    <%= f.collection_select :aircraft_id, Aircraft.all, :id, :pretty_name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :number, 'Flight Number' %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :aircrew_id, 'Aircrew' %><br>
    <%= f.collection_select :aircrew_id, Aircrew.all, :id, :pretty_name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :origin_id, 'Origin' %><br>
    <%= f.collection_select :origin_id, Airport.all, :id, :pretty_name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :destination_id, 'Destination' %><br>
    <%= f.collection_select :destination_id, Airport.all, :id, :pretty_name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :departure_time %><br>
    <%= f.datetime_select :departure_time,  :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :arrival_time %><br>
    <%= f.datetime_select :arrival_time,  :order => [:month, :day, :year] %>
  </div>

  <%= f.hidden_field :request_id %>
  <div class="actions">
    <%= f.submit :class => 'button big gh-black'%>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Edit Airport</h1>

<%= render 'form' %>

<%= link_to 'Show', @airport %> |
<%= link_to 'Back', airport_path %>

app/views/flights/index.html.erb
<h1>Listing of Flights</h1>

<div>
  <%= link_to 'New Flight', new_flight_path %>
</div>

<br>

<%= form_tag flights_path, :method => 'get', :id => "flights_search" do %>
  <div>
    <%= text_field_tag :search, params[:search], :placeholder => 'Search by Flight Number', :size => 45 %>
    <%= submit_tag "Search", :name => nil, :class => 'button big gh-black' %>
  </div>
  <div id="flights"><%= render 'flights' %></div>
<% end %>

app/views/flights/index.js.erb
$("#airports").html("<%= escape_javascript(render("airports")) %>");

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', airports_path %>

app/views/flights/show.html.erb
<h1>Airport Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Flight Number:</strong>
  <%= @flight.number rescue "n/a" %>
</p>

<p>
  <strong>Aircraft Tail Number:</strong>
  <%= @flight.aircraft.tail_number rescue "n/a" %>
</p>
<p>
  <strong>Aircraft Type:</strong>
  <%= "#{@flight.aircraft.aircraft_type.code} - #{@flight.aircraft.aircraft_type.name}" rescue "n/a" %>
</p>
<p>
  <strong>Aircraft Fuel Capacity:</strong>
  <%= @flight.aircraft.fuel_amount rescue "n/a" %>
</p>
<p>
  <strong>Origin Airport:</strong>
  <%= "#{@flight.origin.code} - #{@flight.origin.name}" rescue "n/a" %>
</p>
<p>
  <strong>Destination Airport:</strong>
  <%= "#{@flight.destination.code} - #{@flight.destination.name}" rescue "n/a" %>
</p>
<p>
  <strong>Departure Time:</strong>
  <%= @flight.departure_time rescue "n/a" %>
</p>
<p>
  <strong>Arrival Time:</strong>
  <%= @flight.arrival_time rescue "n/a" %>
</p>

<p>
  <strong>Cargo Contents:</strong>
  <%= @flight.cargo.contents rescue "n/a" %>
</p>
<p>
  <strong>Cargo Weight:</strong>
  <%= @flight.cargo.weight rescue "n/a" %>
</p>

<p>
  <strong>Pilot:</strong>
  <%= "#{@flight.aircrew.pilot.lname}, #{@flight.aircrew.pilot.fname}" rescue "n/a" %>
</p>
<p>
  <strong>Navigator:</strong>
   <%= "#{@flight.aircrew.navigator.lname}, #{@flight.aircrew.navigator.fname}" rescue "n/a" %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>