config/routes.rb
It490::Application.routes.draw do
  resources :aircarft_types

  devise_for :users

  root 'static_pages#home'

  resources :shipment_requests
  get 'shipments' => 'shipments#index'
  get 'cargo' => 'cargo#index'
  resources :aircrafts
  resources :aircraft_types
  resources :aircrews
  resources :airports
  resources :flights
  resources :pilots
  resources :navigators
  resources :user_manager

  

end

app/models/pilot.rb
class Pilot < ActiveRecord::Base
	validates :fname, presence: true
	validates :lname, presence: true

	def self.search(search)
		if search
			where('LOWER(fname) LIKE LOWER(?) or LOWER(lname) LIKE LOWER(?)', "%#{search}%", "%#{search}%")
		else
			scoped
		end
	end
end

app/controllers/pilots_controller.rb
class PilotsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin_filter

  before_action :set_pilot, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  layout 'secure'

  # GET /pilots
  # GET /pilots.json
  def index
     @pilots = Pilot.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 25, :page => params[:page])
  end

  # GET /pilots/1
  # GET /pilots/1.json
  def show
  end

  # GET /pilots/new
  def new
    @pilot = Pilot.new
  end

  # GET /pilots/1/edit
  def edit
  end

  # POST /pilots
  # POST /pilots.json
  def create
    @pilot = Pilot.new(pilot_params)

    respond_to do |format|
      if @pilot.save
        format.html { redirect_to @pilot, notice: 'Pilot was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pilot }
      else
        format.html { render action: 'new' }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pilots/1
  # PATCH/PUT /pilots/1.json
  def update
    respond_to do |format|
      if @pilot.update(pilot_params)
        format.html { redirect_to @pilot, notice: 'Pilot was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pilot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pilots/1
  # DELETE /pilots/1.json
  def destroy
    @pilot.destroy
    respond_to do |format|
      format.html { redirect_to pilots_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pilot
      @pilot = Pilot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pilot_params
      params.require(:pilot).permit(:id, :fname, :lname)
    end

    def sort_column
      Pilot.column_names.include?(params[:sort]) ? params[:sort] : "lname"
    end
  
    def sort_direction
       %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/pilots_helper.rb
module PilotsHelper
end

app/views/pilots/_form.html.erb
<%= form_for(@pilot) do |f| %>
  <% if @pilot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pilot.errors.count, "error") %> prohibited this pilot from being saved:</h2>

      <ul>
      <% @pilot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname, 'First Name' %><br>
    <%= f.text_field :fname, :placeholder => 'First Name', :size => 35 %>
  </div>
  <div class="field">
    <%= f.label :lname, 'Last Name' %><br>
    <%= f.text_field :lname, :placeholder => 'Last Name', :size => 35 %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button big gh-black'%>
  </div>
<% end %>

app/views/pilots/_pilots.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= will_paginate @pilots %>

<table width="600">
	<thead>
		<tr>
			<th><%= sortable "fname", "First Name" %></th>
			<th><%= sortable "lname", "Last Name" %></th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @pilots.each do |pilot| %>
		<tr>
			<td><%= pilot.fname rescue "n/a" %></td>
			<td><%= pilot.lname rescue "n/a" %></td>
			<td><%= link_to 'Show', pilot %></td>
			<td><%= link_to 'Edit', edit_pilot_path(pilot) %></td>
			<td><%= link_to 'Destroy', pilot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %></tbody>
</table>

<%= will_paginate @pilots %>

<br>

app/views/pilots/edit.html.erb
<h1>Edit Pilot</h1>

<%= render 'form' %>

<%= link_to 'Show', @pilot %> |
<%= link_to 'Back', pilot_path %>

app/views/pilots/index.html.erb
<h1>Listing of Pilots</h1>

<div>
  <%= link_to 'New Pilot', new_pilot_path %>
</div>

<br>

<%= form_tag pilots_path, :method => 'get', :id => "pilots_search" do %>
  <div>
    <%= text_field_tag :search, params[:search], :placeholder => 'Search by Name', :size => 45 %>
    <%= submit_tag "Search", :name => nil, :class => 'button big gh-black' %>
  </div>
  <div id="pilots"><%= render 'pilots' %></div>
<% end %>

app/views/pilots/index.js.erb
$("#pilots").html("<%= escape_javascript(render("pilots")) %>");

app/views/pilots/new.html.erb
<h1>New Pilot</h1>

<%= render 'form' %>

<%= link_to 'Back', pilots_path %>

app/views/pilots/show.html.erb
<h1>Pilot Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @pilot.fname rescue "n/a" %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @pilot.lname rescue "n/a" %>
</p>

<%= link_to 'Edit', edit_pilot_path(@pilot) %> |
<%= link_to 'Back', pilots_path %>