config/routes.rb
It490::Application.routes.draw do
  resources :aircarft_types

  devise_for :users

  root 'static_pages#home'

  resources :shipment_requests
  get 'shipments' => 'shipments#index'
  get 'cargo' => 'cargo#index'
  resources :aircrafts
  resources :aircraft_types
  resources :aircrews
  resources :airports
  resources :flights
  resources :pilots
  resources :navigators
  resources :user_manager

  

end

app/models/aircrew.rb
class Aircrew < ActiveRecord::Base
	belongs_to :pilot
	belongs_to :navigator

	def pretty_name
		self.pilot.lname + ", " + self.pilot.fname + " - " + self.navigator.lname + ", " + self.navigator.fname 
	end 
end

app/controllers/aircrews_controller.rb
class AircrewsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin_filter

  before_action :set_aircrew, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  layout 'secure'

  # GET /aircrews
  # GET /aircrews.json
  def index
     #@aircrews = Aircrew.order(sort_direction).paginate(:per_page => 25, :page => params[:page])
     @aircrews = Aircrew.all.paginate(:per_page => 25, :page => params[:page])
  end

  # GET /aircrews/1
  # GET /aircrews/1.json
  def show
  end

  # GET /aircrews/new
  def new
    @aircrew = Aircrew.new
  end

  # GET /aircrews/1/edit
  def edit
  end

  # POST /aircrews
  # POST /aircrews.json
  def create
    @aircrew = Aircrew.new(aircrew_params)

    respond_to do |format|
      if @aircrew.save
        format.html { redirect_to @aircrew, notice: 'Aircrew was successfully created.' }
        format.json { render action: 'show', status: :created, location: @aircrew }
      else
        format.html { render action: 'new' }
        format.json { render json: @aircrew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aircrews/1
  # PATCH/PUT /aircrews/1.json
  def update
    respond_to do |format|
      if @aircrew.update(aircrew_params)
        format.html { redirect_to @aircrew, notice: 'Aircrew was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @aircrew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aircrews/1
  # DELETE /aircrews/1.json
  def destroy
    @aircrew.destroy
    respond_to do |format|
      format.html { redirect_to aircrews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aircrew
      @aircrew = Aircrew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aircrew_params
      params.require(:aircrew).permit(:pilot_id, :navigator_id)
    end
end

app/helpers/aircrews_helper.rb
module AircrewsHelper
end

app/views/aircrews/_aircrews.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>

<%= will_paginate @aircrews %>

<table width="600">
	<thead>
		<tr>
			<th>Crew Id</th>
			<th>Pilot</th>
			<th>Navigator</th>
			<th colspan="3"></th>
		</tr>
	</thead>
	<tbody>
		<% @aircrews.each do |aircrew| %>
		<tr>
			<td><%= aircrew.id rescue "n/a" %></td>
			<td><%= aircrew.pilot.lname + ", " + aircrew.pilot.fname rescue "n/a" %>
			<td><%= aircrew.navigator.lname + ", " + aircrew.navigator.fname rescue "n/a" %></td>
			<td><%= link_to 'Show', aircrew %></td>
			<td><%= link_to 'Edit', edit_aircrew_path(aircrew) %></td>
			<td><%= link_to 'Destroy', aircrew, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %></tbody>
</table>

<%= will_paginate @aircrews %>

<br>

app/views/aircrews/_form.html.erb
<%= form_for(@aircrew) do |f| %>
  <% if @aircrew.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aircrew.errors.count, "error") %> prohibited this aircrew from being saved:</h2>

      <ul>
      <% @aircrew.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pilot_id, 'Pilot' %><br>
    <%= f.select :pilot_id, Pilot.all.collect {|a| ["#{a.lname}, #{a.fname}", a.id]} -%>
  </div>

  <div class="field">
    <%= f.label :navigator_id, 'Navigator' %><br>
    <%= f.select :navigator_id, Navigator.all.collect {|a| ["#{a.lname}, #{a.fname}", a.id]} -%>
  </div>

  <div class="actions">
    <%= f.submit :class => 'button big gh-black'%>
  </div>
<% end %>

app/views/aircrews/edit.html.erb
<h1>Edit Aircrew</h1>

<%= render 'form' %>

<%= link_to 'Show', @aircrew %> |
<%= link_to 'Back', aircrew_path %>

app/views/aircrews/index.html.erb
<h1>Listing of Aircrew</h1>

<div>
  <%= link_to 'New Aircrew', new_aircrew_path %>
</div>

<br>

<%= form_tag aircrews_path, :method => 'get', :id => "aircrews_search" do %>
  <div id="aircrews"><%= render 'aircrews' %></div>
<% end %>

app/views/aircrews/index.js.erb
$("#aircrews").html("<%= escape_javascript(render("aircrews")) %>");

app/views/aircrews/new.html.erb
<h1>New Aircrew</h1>

<%= render 'form' %>

<%= link_to 'Back', aircrews_path %>

app/views/aircrews/show.html.erb
<h1>Aircrew Details</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Pilot:</strong>
  <%= "#{@aircrew.pilot.lname}, #{@aircrew.pilot.fname}" rescue "n/a" %>
</p>

<p>
  <strong>Navigator:</strong>
  <%= "#{@aircrew.navigator.lname}, #{@aircrew.navigator.fname}" rescue "n/a" %>
</p>

<%= link_to 'Edit', edit_aircrew_path(@aircrew) %> |
<%= link_to 'Back', aircrews_path %>